sudo: required

services:
  - docker

cache:
  directories:
  - $HOME/.m2

before_install:
  - docker version
  - docker-compose version
  - apt-cache madison docker-engine

  - sudo service mysql stop       

script:
  - mvn clean package                    # package application
  - cp target/tomcat-pr.war docker/
  - docker-compose up -d                 # start web(tomcat) and database(mysql) containers`
  - sleep 10                             # give db time to start
  - mvn clean compile flyway:migrate     # deploy database schema
  - mvn clean integration-test           # run E2E tests
