sudo: required

services:
  - docker

jdk:
  - oraclejdk8
  
cache:
  directories:
  - $HOME/.m2
  
before_install:
  - "wget http://apache.mirror.iphh.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz && tar xfz apache-maven-3.3.9-bin.tar.gz && sudo mv apache-maven-3.3.9 /usr/local/maven-3.3.9 && sudo rm -f /usr/local/maven && sudo ln -s /usr/local/maven-3.3.9 /usr/local/maven"

script:
  - /usr/local/maven/bin/mvn -version
  - /usr/local/maven/bin/mvn clean verify -Pcd
