version: 2
jobs:
  build:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: circleci/classic:201710-02

    steps:
      - checkout

      - run:
          name: Build application
          command: |
            set -x
            mvn clean package
            cp target/tomcat-pr.war docker/

      - run:
          name: start stack
          command: |
            set -x
            docker-compose up -d
            sleep 10

      - run:
          name: apply db scripts
          command: mvn clean compile flyway:migrate

      - run:
          name: run tests
          command: mvn integration-test
