version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout
      - run:
          name: Build application
          command: mvn clean package

      - run:
          name: Copy jar
          command: cp target/tomcat-pr.war docker/

      - run:
          name: Install Docker Compose
          command: |
            set -x
            VER="1.17.1"
            curl -L https://github.com/docker/compose/releases/download/$VER/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
            docker-compose version

      - setup_remote_docker

      - run:
          name: start stack
          command: |
            set -x
            docker-compose up -d

      - run:
          name: wait for db to start
          command: sleep 10


      - run:
          name: show stack
          command: |
            set -x
            docker-compose ps

      - run:
          name: apply db scripts
          command: mvn clean compile flyway:migrate

      - run:
          name: run tests
          command: mvn integration-test


# dependencies:
# pre:
# - sudo pip install docker-compose
# - docker version
# - docker-compose version

#test:
#  pre:
# - sudo service mysql stop              # stop circleci mysql instance to avoid port clash
# - mvn clean package
# - cp target/tomcat-pr.war docker/
# - docker-compose up -d
# - sleep 10                             # give db time to start
# - mvn clean compile flyway:migrate
# override:
# - mvn integration-test
