version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: mvn clean package
      - run:
          name: Install Docker Compose
          command: |
            set -x
             curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
             chmod +x /usr/local/bin/docker-compose

# dependencies:
# pre:
# - sudo pip install docker-compose
# - docker version
# - docker-compose version

test:
  pre:
# - sudo service mysql stop              # stop circleci mysql instance to avoid port clash
# - mvn clean package
# - cp target/tomcat-pr.war docker/
# - docker-compose up -d
# - sleep 10                             # give db time to start
# - mvn clean compile flyway:migrate
# override:
# - mvn integration-test
